export const regions = {
    eu: [
        'Russia',
        'Germany',
        'United Kingdom',
        'France',
        'Italy',
        'Spain',
        'Ukraine',
        'Poland',
        'Romania',
        'Netherlands',
        'Belgium',
        'Czech Republic',
        'Greece',
        'Portugal',
        'Sweden',
        'Hungary',
        'Belarus',
        'Austria',
        'Serbia',
        'Switzerland',
        'Bulgaria',
        'Denmark',
        'Finland',
        'Slovakia',
        'Norway',
        'Ireland',
        'Croatia',
        'Moldova',
        'Bosnia and Herzegovina',
        'Albania',
        'Lithuania',
        'North Macedonia',
        'Slovenia',
        'Latvia',
        'Estonia',
        'Montenegro',
        'Luxembourg',
        'Malta',
        'Iceland',
        'Andorra',
        'Monaco',
        'Liechtenstein',
        'San Marino',
        'Holy See',
    ],
    na: [
        'United States',
        'Mexico',
        'Canada',
        'Guatemala',
        'Haiti',
        'Cuba',
        'Dominican Republic',
        'Honduras',
        'Nicaragua',
        'El Salvador',
        'Costa Rica',
        'Panama',
        'Jamaica',
        'Puerto Rico',
        'Trinidad and Tobago',
        'Guadeloupe',
        'Belize',
        'Bahamas',
        'Martinique',
        'Barbados',
        'Saint Lucia',
        'Curacao',
        'Grenada',
        'Saint Vincent and the Grenadines',
        'Aruba',
        'United States Virgin Islands',
        'Antigua and Barbuda',
        'Dominica',
        'Cayman Islands',
        'Bermuda',
        'Greenland',
        'Saint Kitts and Nevis',
        'Sint Maarten',
        'Turks and Caicos Islands',
        'Saint Martin',
        'British Virgin Islands',
        'Caribbean Netherlands',
        'Anguilla',
        'Saint Barthelemy',
        'Saint Pierre and Miquelon',
        'Montserrat',
    ],
    sa: [
        'Brazil',
        'Colombia',
        'Argentina',
        'Peru',
        'Venezuela',
        'Chile',
        'Ecuador',
        'Bolivia',
        'Paraguay',
        'Uruguay',
        'Guyana',
        'Suriname',
        'French Guiana',
        'Falkland Islands',
    ],
    as: [
        'China',
        'India',
        'Indonesia',
        'Pakistan',
        'Bangladesh',
        'Japan',
        'Philippines',
        'Vietnam',
        'Turkey',
        'Iran',
        'Thailand',
        'Myanmar',
        'South Korea',
        'Iraq',
        'Afghanistan',
        'Saudi Arabia',
        'Uzbekistan',
        'Malaysia',
        'Yemen',
        'Nepal',
        'North Korea',
        'Taiwan',
        'Sri Lanka',
        'Kazakhstan',
        'Syria',
        'Cambodia',
        'Jordan',
        'Azerbaijan',
        'United Arab Emirates',
        'Tajikistan',
        'Israel',
        'Hong Kong',
        'Laos',
        'Lebanon',
        'Kyrgyzstan',
        'Turkmenistan',
        'Singapore',
        'Oman',
        'State of Palestine',
        'Kuwait',
        'Georgia',
        'Mongolia',
        'Armenia',
        'Qatar',
        'Bahrain',
        'Timor-Leste',
        'Cyprus',
        'Bhutan',
        'Macao',
        'Maldives',
        'Brunei Darussalam',
    ],
    af: [
        'Nigeria',
        'Ethiopia',
        'Egypt',
        'Democratic Republic of the Congo',
        'Tanzania',
        'South Africa',
        'Kenya',
        'Uganda',
        'Algeria',
        'Sudan',
        'Morocco',
        'Angola',
        'Mozambique',
        'Ghana',
        'Madagascar',
        'Cameroon',
        'Cote d\'Ivoire',
        'Niger',
        'Burkina Faso',
        'Mali',
        'Malawi',
        'Zambia',
        'Senegal',
        'Chad',
        'Somalia',
        'Zimbabwe',
        'Guinea',
        'Rwanda',
        'Benin',
        'Burundi',
        'Tunisia',
        'South Sudan',
        'Togo',
        'Sierra Leone',
        'Libya',
        'Congo',
        'Liberia',
        'Central African Republic',
        'Mauritania',
        'Eritrea',
        'Namibia',
        'Gambia',
        'Botswana',
        'Gabon',
        'Lesotho',
        'Guinea-Bissau',
        'Equatorial Guinea',
        'Mauritius',
        'Eswatini',
        'Djibouti',
        'Reunion',
        'Comoros',
        'Western Sahara',
        'Cabo Verde',
        'Mayotte',
        'Sao Tome and Principe',
        'Seychelles',
        'Saint Helena',
    ],
    oc: [
        'Australia',
        'Papua New Guinea',
        'New Zealand',
        'Fiji',
        'Solomon Islands',
        'Micronesia',
        'Vanuatu',
        'New Caledonia',
        'French Polynesia',
        'Samoa',
        'Guam',
        'Kiribati',
        'Tonga',
        'Marshall Islands',
        'Northern Mariana Islands',
        'American Samoa',
        'Palau',
        'Cook Islands',
        'Tuvalu',
        'Wallis and Futuna Islands',
        'Nauru',
        'Niue',
        'Tokelau',
    ]
}

export function countries(): string[] {
    const countries = Object.values(regions).flat();
    countries.sort();

    return countries;
}
